plugins { id 'com.android.application' }
android {
    namespace 'vn.dovanphi.quanmicuatoi'
    compileSdk 35
    defaultConfig {
        applicationId 'vn.dovanphi.quanmicuatoi.androidbeta'
        minSdk 26
        targetSdk 35
        versionCode 18001
        versionName '1.8.0-beta.1'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    buildTypes { release { minifyEnabled false } }
    androidResources { noCompress 'wasm', 'gz', 'whl' }
}
dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test:rules:1.6.1'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.3.0'
}
